export const GET_ALL_APARELHOS = 'GET_ALL_APARELHOS';
export const POST_APARELHO = 'POST_APARELHO';
export const PUT_APARELHO = 'PUT_APARELHO';
export const DELETE_APARELHO = 'DELETE_APARELHO';
export const GET_APARELHOS_NO_LINHAS = 'GET_APARELHOS_NO_LINHAS';
export const POST_BULK_APARELHOS = 'POST_BULK_APARELHOS';