export const LIST_ALL_LINHAS = 'LIST_ALL_LINHAS';
export const ADD_LASTFUNC_2_LINHAS = 'ADD_LASTFUNC_2_LINHAS';
export const ADD_FUNC_2_LINHAS = 'ADD_FUNC_2_LINHAS';
export const ADD_DEVICE_2_LINHAS = 'ADD_DEVICE_2_LINHAS';